Refacto
theopomies/Leace-Monorepo pull request #278
Opened 2023-05-26 04:09 UTC by romain-dfr

2023-06-18 18:45 UTC, theopomies requested changes

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/attributes/AttributesPostForm.tsx
> +              Appartment
Apartment

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/attributes/AttributesUserForm.tsx
> +interface AttributesUserFormProps {
UserAttributesForm (props et nom de fichier)

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/attributes/AttributesUserForm.tsx
> +export function AttributesUserForm({ ...attributes }: AttributesUserFormProps) {
UserAttributesForm

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/moderation/ban/BanModal.tsx
> +      <Button onClick={() => setShowModal(true)}>Ban user</Button>
Utiliser le theme danger

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/moderation/ban/BanUser.tsx
> +        router.push("/moderation/reports");
Pas fan du routeur ailleurs que dans une page genre le root des composants

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/shared/post/PostBarActions.tsx
> +  OnLikeMatch,
On en minuscule

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/shared/post/PostBarActions.tsx
> +  OnDeleteMatch,
On en minuscule

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/shared/post/PostCard.tsx
> +  OnDocValidation?: (document: Document & { url: string }) => Promise<void>;
Minuscule

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/shared/post/PostForm.tsx
> +export interface PostFormProps {
onX encore en minuscule

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/shared/user/UserBar.tsx
> +export interface UserBarProps {
onX encore en minuscule

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/shared/user/UserBarActions.tsx
> +export interface UserBarActionsProps {
onX encore en minuscule

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/shared/user/UserCard.tsx
> +export interface UserCardProps {
onX encore en minuscule

2023-06-18 18:45 UTC, theopomies commented on apps/web/src/components/shared/user/UserForm.tsx
> +export interface UserFormProps {
onX encore en minuscule
J'arrête de l'écrire mais ca vaut pour tous les fichiers

2023-06-22 11:50 UTC, Lybertyxz approved these changes
LGTP (API SIDE)

2023-06-23 08:26 UTC, merged